name: "Pipeline"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pipeline.yml'
      - 'router_events/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - 'codecov.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cov=router_events --cov-report=xml
      - name: Run pylint
        run: poetry run pylint router_events
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: melvyndekort/router-events
          verbose: true

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/melvyndekort/router-events:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
